import { createHash } from "node:crypto";
import { build } from "esbuild";
import { cp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const webRoot = join(__dirname, "..");
const srcRoot = join(webRoot, "src");
const distRoot = join(webRoot, "dist");

await rm(distRoot, { recursive: true, force: true });
await mkdir(join(distRoot, "assets", "vendor"), { recursive: true });
await mkdir(join(distRoot, "assets", "icons"), { recursive: true });

await build({
  entryPoints: [join(srcRoot, "main.js")],
  bundle: true,
  outfile: join(distRoot, "assets", "app.js"),
  minify: true,
  sourcemap: false,
  target: "es2020",
  format: "esm",
  external: ["/assets/vendor/pdf.mjs"],
});

await cp(join(srcRoot, "index.html"), join(distRoot, "index.html"));
await cp(join(srcRoot, "styles.css"), join(distRoot, "assets", "styles.css"));
await cp(join(srcRoot, "manifest.webmanifest"), join(distRoot, "manifest.webmanifest"));
await cp(join(srcRoot, "icons", "icon-192.png"), join(distRoot, "assets", "icons", "icon-192.png"));
await cp(join(srcRoot, "icons", "icon-512.png"), join(distRoot, "assets", "icons", "icon-512.png"));
await cp(join(srcRoot, "icons", "apple-touch-icon.png"), join(distRoot, "assets", "icons", "apple-touch-icon.png"));

const appBytes = await readFile(join(distRoot, "assets", "app.js"));
const cssBytes = await readFile(join(distRoot, "assets", "styles.css"));
const v =
  createHash("sha256").update(appBytes).update(cssBytes).digest("hex").slice(0, 16);
let html = await readFile(join(distRoot, "index.html"), "utf8");
html = html.replace(/href="\/assets\/styles\.css"/, `href="/assets/styles.css?v=${v}"`);
html = html.replace(/src="\/assets\/app\.js"/, `src="/assets/app.js?v=${v}"`);
await writeFile(join(distRoot, "index.html"), html);

await cp(
  join(webRoot, "node_modules", "pdfjs-dist", "build", "pdf.mjs"),
  join(distRoot, "assets", "vendor", "pdf.mjs"),
);
await cp(
  join(webRoot, "node_modules", "pdfjs-dist", "build", "pdf.worker.mjs"),
  join(distRoot, "assets", "vendor", "pdf.worker.mjs"),
);

const precache = [
  "/index.html",
  `/assets/app.js?v=${v}`,
  `/assets/styles.css?v=${v}`,
  "/assets/vendor/pdf.mjs",
  "/assets/vendor/pdf.worker.mjs",
  "/manifest.webmanifest",
  "/assets/icons/icon-192.png",
  "/assets/icons/icon-512.png",
];

const swSource = `/* generated by build.mjs */
const CACHE = "docker-reader-${v}";
const PRECACHE = ${JSON.stringify(precache)};

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE).then((cache) => cache.addAll(PRECACHE)).then(() => self.skipWaiting()),
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))),
    ).then(() => self.clients.claim()),
  );
});

function isDocFilePath(pathname) {
  return /^\\/api\\/doc\\/[^/]+\\/file$/.test(pathname);
}

self.addEventListener("fetch", (event) => {
  const req = event.request;
  if (req.method !== "GET") return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;

  if (isDocFilePath(url.pathname)) {
    event.respondWith(
      fetch(req)
        .then((res) => {
          if (res.ok) {
            const copy = res.clone();
            caches.open(CACHE).then((c) => c.put(req, copy)).catch(() => {});
          }
          return res;
        })
        .catch(() => caches.match(req).then((hit) => hit || Promise.reject(new Error("offline")))),
    );
    return;
  }

  if (req.mode === "navigate") {
    event.respondWith(
      fetch(req).catch(() => caches.match("/index.html")),
    );
    return;
  }

  event.respondWith(
    caches.match(req).then((hit) => {
      if (hit) return hit;
      return fetch(req).then((res) => {
        if (res.ok && url.pathname.startsWith("/assets/")) {
          const copy = res.clone();
          caches.open(CACHE).then((c) => c.put(req, copy)).catch(() => {});
        }
        return res;
      });
    }),
  );
});
`;

await writeFile(join(distRoot, "sw.js"), swSource);
